name: Generate Child Advice

on:
  workflow_dispatch:

jobs:
  generate-advice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get child advice from OpenRouter
        id: get_advice
        run: |
          AGE="1 год 2 месяца" # Можно заменить на нужный возраст
          RESPONSE=$(curl -s -X POST "https://openrouter.ai/api/v1/chat/completions" \
            -H "Authorization: Bearer ${{ secrets.OPENROUTER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "model": "openai/gpt-3.5-turbo",
                  "messages": [
                    {"role": "system", "content": "Ты заботливый детский врач. Дай короткий полезный совет для родителей ребёнка возраста '"$AGE"'."}
                  ]
                }')
          ADVICE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "{\"advice\": \"$ADVICE\", \"age\": \"$AGE\", \"updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > child-advice.json

      - name: Commit and push advice
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add child-advice.json
          git commit -m "update: совет для возраста $AGE"
          git push 